In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
# like a python list index

In [16]:
arr[0:5] = 100 # list böyle çalışmıyor

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
list1 = [1,2,3,4,5] 

In [19]:
list1[:3] = 100

TypeError: can only assign an iterable

In [20]:
list1[:3] = [6,7,8]

In [21]:
list1

[6, 7, 8, 4, 5]

# !

In [25]:
slice_of_arr = arr[0:6]

In [26]:
slice_of_arr[:] = 100

In [27]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [28]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [29]:
# slice of arr not copy of arr is just view of arr

In [30]:
arr_copy = arr.copy()

In [31]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [32]:
arr_copy[:5] = 0

In [33]:
arr_copy

array([  0,   0,   0,   0,   0, 100,   6,   7,   8,   9,  10])

In [34]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [35]:
# see now update

# Matrix

In [36]:
matrix = np.array([[5,10,20],[20,25,30],[35,40,45]])

In [39]:
# or just write
matrix = np.arange(5,50,5)

In [40]:
matrix = matrix.reshape(3,3)

In [41]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
matrix[0][0]

5

In [43]:
matrix[0]

array([ 5, 10, 15])

In [48]:
matrix[1][1]

25

In [50]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [53]:
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [56]:
arr = np.arange(1,11)

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [63]:
arr_2d = np.arange(50).reshape(5,10)

In [64]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
arr_2d > 13

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [68]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])