<p>NumPy (Numerical Python) is use for numerical computation in Python.<br> 
Array-Oriented<br> One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.<br>
ndarrays ---> n dimension arrays
</p>

In [1]:
import numpy as np

## Creating ndarrays
<p>np.array<br>
arr.shape<br>
arr.ndim<br>
    arr.dtype<br>



</p>

In [2]:
data1 = [6,7.5,8,0,1]

In [4]:
arr1 = np.array(data1)
arr1    # 1 dim array or vector

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
arr1.shape

(5,)

In [7]:
data2 = [[1,2,3,4],[5,6,7,8]] # nested list
arr2 = np.array(data2)
arr2 # 2 dim array or matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.shape #2x4 matrix

2


In [12]:
arr2.ndim # two dimension

2

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

### np.zeros() <br> np.ones()

In [15]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr3 = np.zeros((3,2,4))

In [24]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
arr3.shape  

(3, 2, 4)

In [26]:
arr3.ndim

3

### np.arange()

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.arange(15,20,2) # like a range()

array([15, 17, 19])

<strong>array:</strong> Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype
or explicitly specifying a dtype; copies the input data by default<br>
<strong>asarray:</strong> Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list<br>
<strong>ones,
ones_like:</strong>
Produce an array of all 1s with the given shape and dtype; ones_like takes another array and
produces a ones array of the same shape and dtype<br>
<strong>zeros,
zeros_like:</strong>
Like ones and ones_like but producing arrays of 0s instead<br>
<strong>empty,
empty_like:</strong>
Create new arrays by allocating new memory, but do not populate with any values like ones and
zeros<br>
<strong>full,
full_like:</strong>
Produce an array of the given shape and dtype with all values set to the indicated “fill value”
full_like takes another array and produces a filled array of the same shape and dtype<br>
<strong>eye, identity</strong> Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [44]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [46]:
np.ones_like(arr1) # same dimension same row and columns 1s

array([1., 1., 1., 1., 1.])

### np.full()

In [50]:
np.full(4,6)

array([6, 6, 6, 6])

In [51]:
np.full((4,6),2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

### np.eye()

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])