In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x = np.random.randn(8)
y = np.random.randn(8)

In [6]:
x

array([ 1.71562262, -0.06764441, -0.45466696,  0.27973421,  0.95332356,
       -0.40336841, -0.8671391 ,  0.09701743])

In [7]:
y

array([ 0.77044363, -0.71229954, -1.04761958,  0.26012527,  0.60461403,
       -0.10536135,  0.33214302, -1.77934661])

In [8]:
np.maximum(x,y)

array([ 1.71562262, -0.06764441, -0.45466696,  0.27973421,  0.95332356,
       -0.10536135,  0.33214302,  0.09701743])

In [9]:
x * 5

array([ 8.57811308, -0.33822207, -2.27333479,  1.39867103,  4.76661779,
       -2.01684203, -4.33569552,  0.48508713])

In [11]:
np.modf(x)

(array([ 0.71562262, -0.06764441, -0.45466696,  0.27973421,  0.95332356,
        -0.40336841, -0.8671391 ,  0.09701743]),
 array([ 1., -0., -0.,  0.,  0., -0., -0.,  0.]))

In [15]:
remainder, whole_part = np.modf(x)

In [16]:
remainder

array([ 0.71562262, -0.06764441, -0.45466696,  0.27973421,  0.95332356,
       -0.40336841, -0.8671391 ,  0.09701743])

In [17]:
whole_part

array([ 1., -0., -0.,  0.,  0., -0., -0.,  0.])

In [18]:
x

array([ 1.71562262, -0.06764441, -0.45466696,  0.27973421,  0.95332356,
       -0.40336841, -0.8671391 ,  0.09701743])

In [19]:
np.sqrt(x)

C:\Users\sinan\AppData\Local\Temp\ipykernel_8272\393099422.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(x)


array([1.30981778,        nan,        nan, 0.52889905, 0.97638289,
              nan,        nan, 0.3114762 ])

<p><strong>abs, fabs:</strong> Compute the absolute value element-wise for integer, floating-point,or complex values<br>
<strong>sqrt:</strong> Compute the square root of each element (equivalent to arr ** 0.5) <br>
<strong>square:</strong> Compute the square of each element (equivalent to arr ** 2)<br>
<strong>exp:</strong> Compute the exponent ex of each element<br>
<strong>log, log10:</strong>, Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
<br>
<strong>sign:</strong> Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)<br>
<strong>ceil:</strong> Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that
number)<br>
<strong>floor:</strong> Compute the floorof each element (i.e., the largest integer less than or equal to each element)
<strong>rint:</strong> Round elements to the nearest integer, preserving the dtype <br>

<strong>modf:</strong> Return fractional and integral parts of array as a separate array<br>
<strong>isnan:</strong> Return boolean array indicating whether each value is NaN(Not a Number)<br>
<strong>isfinite, isinf: </strong>Return boolean array indicating whether each element is finite(non-inf, non-NaN) or
infinite,
respectively <br>
cos, cosh, sin, 
sinh, tan, tanh
arccos, arccosh, 
arcsin, arcsinh,
arctan, arctanh
logical_not Compute truth value of not xelement-wise (equivalent to ~arr).</p>