In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [5]:
x @ y  # also this is work

array([[ 28,  64],
       [ 67, 181]])

In [6]:
from numpy.linalg import inv,qr

In [7]:
X = np.random.randn(5,5)

In [8]:
X

array([[-1.16905832,  1.13505004, -2.1032475 , -0.94483295,  0.84472014],
       [ 0.15808097,  0.34369377, -0.7777937 , -0.86363804,  1.69916739],
       [ 0.22297822,  0.29280956,  0.7308527 ,  0.74673668, -0.94537061],
       [ 0.40070432, -2.27557108,  0.08277414, -0.17200085,  0.37150251],
       [-0.11614284, -2.00343619, -1.08179153,  1.14403099, -2.04390896]])

In [10]:
mat = X.T.dot(X) #np.dot(X.T,X)

In [11]:
inv(mat)

array([[ 111.4372742 ,   16.13626391,  -18.56099385, -169.28400372,
        -107.91172108],
       [  16.13626391,    2.47679981,   -2.77155978,  -24.02077759,
         -15.41242023],
       [ -18.56099385,   -2.77155978,    3.54105885,   26.33293865,
          16.95938482],
       [-169.28400372,  -24.02077759,   26.33293865,  268.9393437 ,
         170.53470457],
       [-107.91172108,  -15.41242023,   16.95938482,  170.53470457,
         108.35328951]])

In [13]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.77635684e-14,  8.88178420e-15,
         9.94759830e-14,  4.26325641e-14],
       [ 5.68434189e-14,  1.00000000e+00,  0.00000000e+00,
         1.13686838e-13,  5.68434189e-14],
       [-2.84217094e-14,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  2.84217094e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00],
       [-2.27373675e-13,  0.00000000e+00,  2.84217094e-14,
         2.27373675e-13,  1.00000000e+00]])

In [15]:
q, r = qr(mat) #QR Fac

<strong>diag:</strong> Return the diagonal (or off-diagonal)elements of a square matrix as a 1D array, or convert a 1D array into a square
matrix with zeros on the off-diagonal<br>
<strong>dot:</strong> Matrix multiplication<br>
<strong>trace:</strong> Compute the sum of the diagonal elements
det Compute the matrix determinant

## 4.6 Pseudorandom Number Generation

<strong>seed:</strong> Seed the random number generator permutation Return a random permutation of a sequence, or return a
permuted range<br>
<strong>shuffle</strong> Randomly permute a sequence in-place<br>
<strong>rand</strong> Draw samples from a uniform distribution<br>
<strong>randint</strong> Draw random integers from a given low-to-high range<br>
<strong>randn</strong> Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)<br>
<strong>binomial</strong> Draw samples from a binomial distribution<br>
<strong>normal</strong> Draw samples from a normal (Gaussian) distribution<br>
<strong>beta</strong> Draw samples from a beta distribution<br>
<strong>chisquare</strong>
Draw samples from a chi-square distribution<br>
<strong>gamma</strong> Draw samples from a gamma distribution<br>
<strong>uniform</strong> Draw samples from a uniform [0, 1) distribution