In [2]:
import numpy as np

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [4]:
arr_border = np.random.randint(2,5,size = (5,5))
arr_border[1:4,1:4] = 0
arr_border[[0,-1],:] = 1
arr_border[:,[0,-1]] = 1
print(arr_border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### First we need to know np.diag()

In [6]:
matrix = np.diag([7,7,7,7])
matrix

array([[7, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 7]])

In [10]:
# Solution
matrix = np.diag([6,6,6],k=-1)
matrix

array([[0, 0, 0, 0],
       [6, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 6, 0]])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [55]:
matrix_5x3 = np.random.randint(0,4,size = (5,3))
matrix_3x2 = np.random.randint(0,4,size = (3,2))
matrix = np.matmul(matrix_5x3,matrix_3x2)
print(matrix)

[[15  5]
 [ 6  0]
 [13  3]
 [11  4]
 [ 6  2]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [11]:
arr1D = np.arange(15)
arr1D[3:9] *= -1
print(arr1D)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14]
