In [ ]:
# shift + tab ile functionların içine bakmayı unutma

<p>NumPy (Numerical Python) is use for numerical computation in Python.<br> 
Array-Oriented<br> One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.<br>
ndarrays ---> n dimension arrays
</p>

In [1]:
import numpy as np

## Creating ndarrays
<p>np.array<br>
arr.shape<br>
arr.ndim<br>
    arr.dtype<br>



</p>

In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
arr1 = np.array(data1)
arr1    # 1 dim array or vector

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
arr1.shape

(5,)

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]] # nested list
arr2 = np.array(data2)
arr2 # 2 dim array or matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.shape #2x4 matrix

(2, 4)

In [7]:
arr2.ndim # two dimension

2

In [8]:
arr1.dtype

dtype('float64')

In [9]:
arr2.dtype

dtype('int32')

### np.zeros() <br> np.ones()

In [10]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr3 = np.zeros((3,2,4))

In [15]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
arr3.shape  

(3, 2, 4)

In [17]:
arr3.ndim

3

### np.arange()

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(15,20,2) # like a range()

array([15, 17, 19])

<strong>array:</strong> Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype
or explicitly specifying a dtype; copies the input data by default<br>
<strong>asarray:</strong> Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list<br>
<strong>ones,
ones_like:</strong>
Produce an array of all 1s with the given shape and dtype; ones_like takes another array and
produces a ones array of the same shape and dtype<br>
<strong>zeros,
zeros_like:</strong>
Like ones and ones_like but producing arrays of 0s instead<br>
<strong>empty,
empty_like:</strong>
Create new arrays by allocating new memory, but do not populate with any values like ones and
zeros<br>
<strong>full,
full_like:</strong>
Produce an array of the given shape and dtype with all values set to the indicated “fill value”
full_like takes another array and produces a filled array of the same shape and dtype<br>
<strong>eye, identity</strong> Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [20]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
np.ones_like(arr1) # same dimension same row and columns 1s

array([1., 1., 1., 1., 1.])

### np.full()

In [22]:
np.full(4,6)

array([6, 6, 6, 6])

In [23]:
np.full((4,6),2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

### np.eye()

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Convert Array<br>
arr.astype(np.int32 or np.float64)

In [25]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
arr1 = np.array([1.1,2.8,3.2])
arr.dtype

dtype('int32')

In [29]:
float_arr1 = arr1.astype(np.int32)

In [30]:
float_arr1

array([1, 2, 3])

In [31]:
#or
print(arr)
print(arr1)

[1 2 3 4 5]
[1.1 2.8 3.2]


In [32]:
new_arr = arr.astype(arr1.dtype)

In [33]:
new_arr  

array([1., 2., 3., 4., 5.])

### Arithmetic with NumPy Arrays

In [34]:
arr = np.array([[1,2,3],[4,5,6]])

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr * arr  #element_wise

array([[ 1,  4,  9],
       [16, 25, 36]])

In [37]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [39]:
arr **0.5 # Element_Wise

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [40]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### arr.reshape(())

In [41]:
arr = np.arange(9)

In [42]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr3x3 = arr.reshape((3,3))

In [44]:
arr3x3 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
arr3x3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Concatenating ,vstack and hstack

In [46]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [47]:
np.concatenate([arr1,arr2],axis= 0) #axis=0 x altalta

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
np.concatenate([arr1,arr2],axis= 1) #axis=1 y yanyana

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [49]:
# or

In [50]:
np.vstack((arr1,arr2))  #vertical_stack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
np.hstack((arr1,arr2))  #horizantal_stack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### split()

In [52]:
arr = np.random.randn(4,6)

In [53]:
arr

array([[-0.42018938,  0.07376131, -1.03737029, -0.4140326 ,  1.12872835,
        -1.1784491 ],
       [ 0.59554636, -0.43532597,  0.45434634,  0.29868912, -0.25786827,
        -1.42648702],
       [-0.15954355,  1.20536681,  2.65437449,  0.72261351,  0.60906772,
        -0.46267221],
       [-1.51731803, -1.07713199,  1.46023733, -0.47593567, -1.09767152,
         0.92895513]])

In [54]:
np.split(arr,2)  # row wise split 2 list

[array([[-0.42018938,  0.07376131, -1.03737029, -0.4140326 ,  1.12872835,
         -1.1784491 ],
        [ 0.59554636, -0.43532597,  0.45434634,  0.29868912, -0.25786827,
         -1.42648702]]),
 array([[-0.15954355,  1.20536681,  2.65437449,  0.72261351,  0.60906772,
         -0.46267221],
        [-1.51731803, -1.07713199,  1.46023733, -0.47593567, -1.09767152,
          0.92895513]])]

In [55]:
np.split(arr,4) # row wise split 4 list

[array([[-0.42018938,  0.07376131, -1.03737029, -0.4140326 ,  1.12872835,
         -1.1784491 ]]),
 array([[ 0.59554636, -0.43532597,  0.45434634,  0.29868912, -0.25786827,
         -1.42648702]]),
 array([[-0.15954355,  1.20536681,  2.65437449,  0.72261351,  0.60906772,
         -0.46267221]]),
 array([[-1.51731803, -1.07713199,  1.46023733, -0.47593567, -1.09767152,
          0.92895513]])]

In [56]:
np.hsplit(arr,3)  # column wise split 3 list

[array([[-0.42018938,  0.07376131],
        [ 0.59554636, -0.43532597],
        [-0.15954355,  1.20536681],
        [-1.51731803, -1.07713199]]),
 array([[-1.03737029, -0.4140326 ],
        [ 0.45434634,  0.29868912],
        [ 2.65437449,  0.72261351],
        [ 1.46023733, -0.47593567]]),
 array([[ 1.12872835, -1.1784491 ],
        [-0.25786827, -1.42648702],
        [ 0.60906772, -0.46267221],
        [-1.09767152,  0.92895513]])]

In [57]:
arr_split = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [58]:
arr_split

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
np.split(arr_split,[2,3]) # bunu anlamadım

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

### Basic Indexing and Slicing

In [60]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[5]

5

In [62]:
arr[5:8]

array([5, 6, 7])

In [63]:
arr[5:8] = 13

In [64]:
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [65]:
# # As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
# propagated (or broadcasted henceforth) to the entire selection.

An important first distinction
from Python’s built-in lists is that array slices are views on the original array.
This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [66]:
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [67]:
arr_slice = arr[5:8]

In [68]:
arr_slice

array([13, 13, 13])

In [69]:
arr_slice[1] = 12345

In [70]:
arr

array([    0,     1,     2,     3,     4,    13, 12345,    13,     8,
           9])

In [71]:
arr_slice[:] = 64

In [72]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
# Data is not copied changing reflect main data

In [74]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [75]:
arr_slice_copy = arr[5:8].copy()

In [76]:
arr_slice_copy

array([64, 64, 64])

In [77]:
arr_slice_copy[:] = 12341234

In [78]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [79]:
arr_slice_copy

array([12341234, 12341234, 12341234])

In [80]:
# If you want a copy of a slice of an ndarray instead of a view, you
# will need to explicitly copy the array—for example,
# arr[5:8].copy().

In [81]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [82]:
arr2d[1]

array([4, 5, 6])

In [83]:
arr2d[0][2]

3

In [84]:
# or write
arr2d[0,2]

3

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2,1:] 

array([[2, 3],
       [5, 6]])

# Boolean Indexing

In [88]:
names = np.array(["Bob","Joe","Will","Bob","will","Joe","Joe"])

In [89]:
data = np.random.randn(7,4)

In [90]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'will', 'Joe', 'Joe'], dtype='<U4')

In [91]:
data

array([[-1.0336282 , -0.73033826,  2.31046457, -0.41934247],
       [ 1.05389347,  0.87153063,  0.61921181,  0.45000861],
       [ 0.02476501, -1.04789398, -0.40949983, -1.11394201],
       [-0.40207815, -0.74309753,  1.82900909,  0.23522723],
       [ 0.27320687, -0.02142031,  0.45183069, -1.95337214],
       [-0.8184771 ,  2.21685702,  0.68063304,  0.58227374],
       [-1.12483973,  1.20069604,  0.51992958,  0.53367161]])

In [92]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [93]:
data[names == "Bob"]  # 0 and 3 index return since True 

array([[-1.0336282 , -0.73033826,  2.31046457, -0.41934247],
       [-0.40207815, -0.74309753,  1.82900909,  0.23522723]])

In [94]:
data[names == "Bob", 2:]

array([[ 2.31046457, -0.41934247],
       [ 1.82900909,  0.23522723]])

In [95]:
# The Python keywords and and or do not work with boolean arrays.
# Use & (and) and | (or) instead.

In [114]:
names = np.array(["Bob","Joe","Will","Bob"])

In [115]:
data1 = np.random.randn(6,4)

In [116]:
data1

array([[-2.37469494,  1.25080746, -1.76707662, -0.29355272],
       [ 1.0091304 ,  0.21191404, -0.73060321,  1.51188122],
       [ 0.69239874,  1.15530966,  0.30701899,  1.36833518],
       [-0.20518375, -1.00696487, -1.18074517, -2.06775901],
       [-0.31024345,  1.62905307, -0.63343167,  1.48481027],
       [-1.94896858,  1.82520948,  0.28022911,  0.98892826]])

In [117]:
data1[:,names == "Bob"]

array([[-2.37469494, -0.29355272],
       [ 1.0091304 ,  1.51188122],
       [ 0.69239874,  1.36833518],
       [-0.20518375, -2.06775901],
       [-0.31024345,  1.48481027],
       [-1.94896858,  0.98892826]])

### Fancy Indexing 

In [96]:
arr = np.empty((8,4))

In [97]:
for i in range(8):
    arr[i] = i

In [98]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [99]:
arr[[4,3,0,6]] # Select 4 index, 3 index, 0 index, 6 index

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [100]:
arr = np.arange(32).reshape((8,4))

In [101]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [102]:
arr[[1,5,7,2],[0,3,1,2]]
#(1,0),(5,3),(7,1),(2,2)

array([ 4, 23, 29, 10])

### Transposing Arrays and Swapping Axes

In [103]:
arr = np.arange(15).reshape((3, 5))

In [104]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [105]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])