In [1]:
# shift + tab ile functionların içine bakmayı unutma

<p>NumPy (Numerical Python) is use for numerical computation in Python.<br> 
Array-Oriented<br> One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.<br>
ndarrays ---> n dimension arrays
</p>

In [2]:
import numpy as np

## Creating ndarrays
<p>np.array<br>
arr.shape<br>
arr.ndim<br>
    arr.dtype<br>



</p>

In [3]:
data1 = [6,7.5,8,0,1]

In [4]:
arr1 = np.array(data1)
arr1    # 1 dim array or vector

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
arr1.shape

(5,)

In [6]:
data2 = [[1,2,3,4],[5,6,7,8]] # nested list
arr2 = np.array(data2)
arr2 # 2 dim array or matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape #2x4 matrix

(2, 4)

In [8]:
arr2.ndim # two dimension

2

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

### np.zeros() <br> np.ones()

In [11]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr3 = np.zeros((3,2,4))

In [16]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
arr3.shape  

(3, 2, 4)

In [18]:
arr3.ndim

3

### np.arange()

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(15,20,2) # like a range()

array([15, 17, 19])

<strong>array:</strong> Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype
or explicitly specifying a dtype; copies the input data by default<br>
<strong>asarray:</strong> Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list<br>
<strong>ones,
ones_like:</strong>
Produce an array of all 1s with the given shape and dtype; ones_like takes another array and
produces a ones array of the same shape and dtype<br>
<strong>zeros,
zeros_like:</strong>
Like ones and ones_like but producing arrays of 0s instead<br>
<strong>empty,
empty_like:</strong>
Create new arrays by allocating new memory, but do not populate with any values like ones and
zeros<br>
<strong>full,
full_like:</strong>
Produce an array of the given shape and dtype with all values set to the indicated “fill value”
full_like takes another array and produces a filled array of the same shape and dtype<br>
<strong>eye, identity</strong> Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [21]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
np.ones_like(arr1) # same dimension same row and columns 1s

array([1., 1., 1., 1., 1.])

### np.full()

In [23]:
np.full(4,6)

array([6, 6, 6, 6])

In [24]:
np.full((4,6),2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

### np.eye()

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Convert Array<br>
arr.astype(np.int32 or np.float64)

In [26]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [27]:
float_arr = arr.astype(np.float64)

In [28]:
float_arr

array([1., 2., 3., 4., 5.])

In [29]:
arr1 = np.array([1.1,2.8,3.2])
arr.dtype

dtype('int32')

In [30]:
float_arr1 = arr1.astype(np.int32)

In [31]:
float_arr1

array([1, 2, 3])

In [32]:
#or
print(arr)
print(arr1)

[1 2 3 4 5]
[1.1 2.8 3.2]


In [33]:
new_arr = arr.astype(arr1.dtype)

In [34]:
new_arr  

array([1., 2., 3., 4., 5.])

### Arithmetic with NumPy Arrays

In [35]:
arr = np.array([[1,2,3],[4,5,6]])

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr * arr  #element_wise

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr **0.5 # Element_Wise

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### arr.reshape(())

In [42]:
arr = np.arange(9)

In [43]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr3x3 = arr.reshape((3,3))

In [45]:
arr3x3 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
arr3x3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Concatenating ,vstack and hstack

In [47]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [48]:
np.concatenate([arr1,arr2],axis= 0) #axis=0 x altalta

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
np.concatenate([arr1,arr2],axis= 1) #axis=1 y yanyana

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [50]:
# or

In [51]:
np.vstack((arr1,arr2))  #vertical_stack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
np.hstack((arr1,arr2))  #horizantal_stack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### split()

In [53]:
arr = np.random.randn(4,6)

In [54]:
arr

array([[-0.59757122,  1.16008743,  2.4756288 , -0.50566289, -1.86401201,
        -0.31742358],
       [-2.17705458,  0.78723661,  1.77571464, -1.0011283 ,  0.87824027,
         1.1424989 ],
       [-0.20784749,  0.34372887,  0.41808252,  0.05994582,  1.54326211,
         3.11897388],
       [-2.52394804,  0.68615557, -0.68241309,  0.03137642, -0.71194847,
        -0.25693208]])

In [55]:
np.split(arr,2)  # row wise split 2 list

[array([[-0.59757122,  1.16008743,  2.4756288 , -0.50566289, -1.86401201,
         -0.31742358],
        [-2.17705458,  0.78723661,  1.77571464, -1.0011283 ,  0.87824027,
          1.1424989 ]]),
 array([[-0.20784749,  0.34372887,  0.41808252,  0.05994582,  1.54326211,
          3.11897388],
        [-2.52394804,  0.68615557, -0.68241309,  0.03137642, -0.71194847,
         -0.25693208]])]

In [56]:
np.split(arr,4) # row wise split 4 list

[array([[-0.59757122,  1.16008743,  2.4756288 , -0.50566289, -1.86401201,
         -0.31742358]]),
 array([[-2.17705458,  0.78723661,  1.77571464, -1.0011283 ,  0.87824027,
          1.1424989 ]]),
 array([[-0.20784749,  0.34372887,  0.41808252,  0.05994582,  1.54326211,
          3.11897388]]),
 array([[-2.52394804,  0.68615557, -0.68241309,  0.03137642, -0.71194847,
         -0.25693208]])]

In [57]:
np.hsplit(arr,3)  # column wise split 3 list

[array([[-0.59757122,  1.16008743],
        [-2.17705458,  0.78723661],
        [-0.20784749,  0.34372887],
        [-2.52394804,  0.68615557]]),
 array([[ 2.4756288 , -0.50566289],
        [ 1.77571464, -1.0011283 ],
        [ 0.41808252,  0.05994582],
        [-0.68241309,  0.03137642]]),
 array([[-1.86401201, -0.31742358],
        [ 0.87824027,  1.1424989 ],
        [ 1.54326211,  3.11897388],
        [-0.71194847, -0.25693208]])]

In [58]:
arr_split = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [59]:
arr_split

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
np.split(arr_split,[2,3]) # bunu anlamadım

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

### Basic Indexing and Slicing

In [61]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 13

In [65]:
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [66]:
# # As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
# propagated (or broadcasted henceforth) to the entire selection.

In [67]:
# An important first distinction
# from Python’s built-in lists is that array slices are views on the original array.
# This means that the data is not copied, and any modifications to the view will be
# reflected in the source array.

In [68]:
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [69]:
arr_slice = arr[5:8]

In [70]:
arr_slice

array([13, 13, 13])

In [71]:
arr_slice[1] = 12345

In [72]:
arr

array([    0,     1,     2,     3,     4,    13, 12345,    13,     8,
           9])

In [73]:
arr_slice[:] = 64

In [74]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [75]:
# Data is not copied changing reflect main data

In [76]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [77]:
arr_slice_copy = arr[5:8].copy()

In [78]:
arr_slice_copy

array([64, 64, 64])

In [79]:
arr_slice_copy[:] = 12341234

In [80]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [81]:
arr_slice_copy

array([12341234, 12341234, 12341234])

In [82]:
# If you want a copy of a slice of an ndarray instead of a view, you
# will need to explicitly copy the array—for example,
# arr[5:8].copy().

In [83]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [84]:
arr2d[1]

array([4, 5, 6])

In [85]:
arr2d[0][2]

3

In [86]:
# or write also
arr2d[0,2]

3

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr2d[:2,1:] 

array([[2, 3],
       [5, 6]])

# Boolean Indexing

In [90]:
names = np.array(["Bob","Joe","Will","Bob","will","Joe","Joe"])

In [91]:
data = np.random.randn(7,4)

In [92]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'will', 'Joe', 'Joe'], dtype='<U4')

In [93]:
data

array([[-0.97774423,  0.10303278, -0.81448236,  0.33563207],
       [-2.15261175, -1.55593662,  0.67150754,  0.28064117],
       [ 1.1785836 , -1.55305787,  1.50559785, -1.77440639],
       [ 0.80758915,  1.22189879,  0.85091214,  0.12449785],
       [ 1.50354852,  1.30821334,  0.77356361,  0.47759688],
       [ 0.59324421, -1.12494184,  0.22034668,  1.09548575],
       [-0.12294614, -0.4355796 ,  0.88549866, -0.51259355]])

In [94]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [95]:
data[names == "Bob"]  # 0 and 3 index return since True 

array([[-0.97774423,  0.10303278, -0.81448236,  0.33563207],
       [ 0.80758915,  1.22189879,  0.85091214,  0.12449785]])

In [96]:
data[names == "Bob", 2:]

array([[-0.81448236,  0.33563207],
       [ 0.85091214,  0.12449785]])

In [97]:
# The Python keywords and and or do not work with boolean arrays.
# Use & (and) and | (or) instead.

In [98]:
names = np.array(["Bob","Joe","Will","Bob"])

In [99]:
data1 = np.random.randn(6,4)

In [100]:
data1

array([[-0.20863372, -0.55738145,  0.65945715, -0.34275586],
       [-1.02654517, -0.55715088, -0.4546129 , -0.8305768 ],
       [ 2.26464862, -0.49688258,  1.22413857, -1.86289421],
       [-1.01931807,  0.3334496 ,  0.99794755,  0.38505285],
       [ 0.40261412,  1.54543093,  0.63665742,  1.16195422],
       [-0.66900975,  0.54014166, -0.16212987,  0.05365166]])

In [101]:
data1[:,names == "Bob"]  #[T,F,F,T]

array([[-0.20863372, -0.34275586],
       [-1.02654517, -0.8305768 ],
       [ 2.26464862, -1.86289421],
       [-1.01931807,  0.38505285],
       [ 0.40261412,  1.16195422],
       [-0.66900975,  0.05365166]])

### Fancy Indexing 

In [102]:
arr = np.empty((8,4))

In [103]:
for i in range(8):
    arr[i] = i

In [104]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [105]:
arr[[4,3,0,6]] #! Select 4 index, 3 index, 0 index, 6 index

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [106]:
arr = np.arange(32).reshape((8,4))

In [107]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [108]:
arr[[1,5,7,2],[0,3,1,2]]
#(1,0),(5,3),(7,1),(2,2)

array([ 4, 23, 29, 10])

### Transposing Arrays and Swapping Axes

In [109]:
arr = np.arange(15).reshape((3, 5))

In [110]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [111]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])