# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list) # 1 dimensional array (vector)

array([1, 2, 3])

In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(matrix) # 2 dim array (matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)    # 0 to 9  vector 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,20,2) # 0 to 20 step 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros(3)  

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10) # vector from 0 to 5 between 10

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.linspace(1,10,10) # 1 dim

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.eye(4) # ıdentity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# np.random.rand  

<strong> Uniformly distributed values</strong>


In [16]:
np.random.rand()

0.8032274998020702

In [17]:
np.random.rand(5)     # random dist. [0,1) (Uniformly distributed values.) 

array([0.75861612, 0.63246519, 0.12119889, 0.35294098, 0.18724059])

In [18]:
np.random.rand(3,3)  # 3x3 matrix with uniformly distr values

array([[0.57738942, 0.05802192, 0.26080396],
       [0.61578933, 0.00210218, 0.68836013],
       [0.1722056 , 0.31378632, 0.78363276]])

# np.random.randn

<strong>Normally (Gaussian) distributed values.</strong>

In [19]:
np.random.randn()

-0.6136914059737044

In [20]:
np.random.randn(3) # centered around 0 (randomly return number near to 0)

array([-0.8033439 ,  0.70105494,  2.86697772])

In [21]:
np.random.randn(3,6)

array([[-0.52746386, -0.69014659, -0.90124143,  0.53715278,  0.15926489,
         1.23057707],
       [ 0.51189608,  1.28149139,  0.67929005, -0.27476791,  0.80084189,
        -0.56810531],
       [-1.19507254, -0.46224762, -0.44912835, -1.20076991,  0.00330678,
        -0.18798252]])

## np.random.randint

In [22]:
np.random.randint(1,100) #give number between 1 to 100 100 not included

58

In [23]:
np.random.randint(1,100,10) # 10 random number

array([43, 31, 38, 48, 94, 69, 40,  2, 70, 24])

# .reshape()

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([39, 27, 33, 18, 16, 42, 18, 38,  6,  7])

In [28]:
arr.reshape(5,5)  # make it 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.reshape(5,2) # make it 5x2 matrix

array([[39, 27],
       [33, 18],
       [16, 42],
       [18, 38],
       [ 6,  7]])

# .max() and .min()

In [30]:
ranarr

array([39, 27, 33, 18, 16, 42, 18, 38,  6,  7])

In [31]:
ranarr.max()

42

In [32]:
ranarr.min()

6

# .argmax() .argmin()

<strong>give max number index</strong>

In [33]:
ranarr.argmax()

5

In [34]:
ranarr1 = ranarr.reshape(2,5)

In [35]:
ranarr1

array([[39, 27, 33, 18, 16],
       [42, 18, 38,  6,  7]])

In [36]:
ranarr1.argmax() # not changing

5

# .shape

In [37]:
ranarr.shape

(10,)

In [38]:
ranarr1.shape

(2, 5)

In [39]:
ranarr2 = ranarr.reshape(10,1)

In [40]:
ranarr2

array([[39],
       [27],
       [33],
       [18],
       [16],
       [42],
       [18],
       [38],
       [ 6],
       [ 7]])

In [41]:
ranarr2.shape

(10, 1)

In [42]:
arr.dtype

dtype('int32')

In [44]:
from numpy.random import randint

In [45]:
randint(2,10)

6